"""Stable Phase 10 notification values shared across backend layers."""

from enum import StrEnum


def enum_values(enum_class: type[StrEnum]) -> list[str]:
    """Persist enum values rather than Python member names."""

    return [member.value for member in enum_class]


class NotificationEventType(StrEnum):
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_REPLACED = "DOCUMENT_REPLACED"
    DOCUMENT_REVISION_CREATED = "DOCUMENT_REVISION_CREATED"
    EXTRACTION_COMPLETED = "EXTRACTION_COMPLETED"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    OCR_COMPLETED = "OCR_COMPLETED"
    OCR_FAILED = "OCR_FAILED"
    LANGUAGE_DETECTION_COMPLETED = "LANGUAGE_DETECTION_COMPLETED"
    COMPLIANCE_VALIDATION_COMPLETED = "COMPLIANCE_VALIDATION_COMPLETED"
    COMPLIANCE_VALIDATION_FAILED = "COMPLIANCE_VALIDATION_FAILED"
    SIMILARITY_COMPLETED = "SIMILARITY_COMPLETED"
    GLOSSARY_VALIDATION_COMPLETED = "GLOSSARY_VALIDATION_COMPLETED"
    CRITICAL_FINDING_CREATED = "CRITICAL_FINDING_CREATED"
    MAJOR_FINDING_CREATED = "MAJOR_FINDING_CREATED"
    FINDING_ASSIGNED = "FINDING_ASSIGNED"
    FINDING_RESOLVED = "FINDING_RESOLVED"
    FINDING_REOPENED = "FINDING_REOPENED"
    ACCEPTED_RISK_EXPIRING = "ACCEPTED_RISK_EXPIRING"
    SHAREPOINT_SYNC_COMPLETED = "SHAREPOINT_SYNC_COMPLETED"
    SHAREPOINT_SYNC_PARTIAL = "SHAREPOINT_SYNC_PARTIAL"
    SHAREPOINT_SYNC_FAILED = "SHAREPOINT_SYNC_FAILED"
    SHAREPOINT_CONFLICT_CREATED = "SHAREPOINT_CONFLICT_CREATED"
    SHAREPOINT_CONNECTION_FAILED = "SHAREPOINT_CONNECTION_FAILED"
    GRAPH_SUBSCRIPTION_RENEWAL_FAILED = "GRAPH_SUBSCRIPTION_RENEWAL_FAILED"
    REPORT_GENERATED = "REPORT_GENERATED"
    REPORT_FAILED = "REPORT_FAILED"
    SYSTEM_BACKUP_FAILED = "SYSTEM_BACKUP_FAILED"
    SYSTEM_DISK_SPACE_LOW = "SYSTEM_DISK_SPACE_LOW"
    SYSTEM_WORKER_UNAVAILABLE = "SYSTEM_WORKER_UNAVAILABLE"
    SYSTEM_SECURITY_ALERT = "SYSTEM_SECURITY_ALERT"


SYSTEM_CRITICAL_NOTIFICATION_EVENTS = frozenset(
    {
        NotificationEventType.SYSTEM_BACKUP_FAILED,
        NotificationEventType.SYSTEM_DISK_SPACE_LOW,
        NotificationEventType.SYSTEM_WORKER_UNAVAILABLE,
        NotificationEventType.SYSTEM_SECURITY_ALERT,
        NotificationEventType.GRAPH_SUBSCRIPTION_RENEWAL_FAILED,
    }
)


class NotificationChannel(StrEnum):
    IN_APP = "IN_APP"
    EMAIL_GRAPH = "EMAIL_GRAPH"
    TEAMS = "TEAMS"
    TELEGRAM = "TELEGRAM"


class NotificationContentType(StrEnum):
    PLAIN_TEXT = "PLAIN_TEXT"
    HTML = "HTML"
    MARKDOWN = "MARKDOWN"
    JSON_CARD = "JSON_CARD"


class NotificationScopeType(StrEnum):
    GLOBAL = "GLOBAL"
    DEPARTMENT = "DEPARTMENT"
    DOCUMENT_TYPE = "DOCUMENT_TYPE"
    DEPARTMENT_DOCUMENT_TYPE = "DEPARTMENT_DOCUMENT_TYPE"


class NotificationRecipientType(StrEnum):
    EVENT_ACTOR = "EVENT_ACTOR"
    DOCUMENT_OWNER = "DOCUMENT_OWNER"
    DOCUMENT_CONTROLLER = "DOCUMENT_CONTROLLER"
    DEPARTMENT_USERS = "DEPARTMENT_USERS"
    ROLE = "ROLE"
    SPECIFIC_USERS = "SPECIFIC_USERS"
    SPECIFIC_EMAILS = "SPECIFIC_EMAILS"
    TEAMS_CHANNEL = "TEAMS_CHANNEL"
    TELEGRAM_CHAT = "TELEGRAM_CHAT"


class NotificationDigestMode(StrEnum):
    NONE = "NONE"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"


class NotificationSeverity(StrEnum):
    INFORMATION = "INFORMATION"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class NotificationDeliveryStatus(StrEnum):
    QUEUED = "QUEUED"
    SENDING = "SENDING"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


TERMINAL_NOTIFICATION_DELIVERY_STATUSES = frozenset(
    {
        NotificationDeliveryStatus.SENT,
        NotificationDeliveryStatus.DELIVERED,
        NotificationDeliveryStatus.CANCELLED,
        NotificationDeliveryStatus.SKIPPED,
    }
)
