"""Canonical Phase 10 SharePoint and Microsoft Graph lifecycle values."""

from enum import StrEnum


def enum_values(enum_class: type[StrEnum]) -> list[str]:
    return [member.value for member in enum_class]


class SharePointAuthMode(StrEnum):
    CLIENT_SECRET = "CLIENT_SECRET"
    CERTIFICATE = "CERTIFICATE"


class SharePointConnectionStatus(StrEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    CONNECTED = "CONNECTED"
    DEGRADED = "DEGRADED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    UNAVAILABLE = "UNAVAILABLE"
    DISABLED = "DISABLED"


class FolderMappingScope(StrEnum):
    GLOBAL = "GLOBAL"
    DEPARTMENT = "DEPARTMENT"
    SECTION = "SECTION"
    DOCUMENT_TYPE = "DOCUMENT_TYPE"
    DEPARTMENT_DOCUMENT_TYPE = "DEPARTMENT_DOCUMENT_TYPE"
    SECTION_DOCUMENT_TYPE = "SECTION_DOCUMENT_TYPE"


class MetadataDataType(StrEnum):
    STRING = "STRING"
    INTEGER = "INTEGER"
    BOOLEAN = "BOOLEAN"
    DATE = "DATE"
    DATETIME = "DATETIME"
    CHOICE = "CHOICE"
    LOOKUP_TEXT = "LOOKUP_TEXT"
    USER_DISPLAY_NAME = "USER_DISPLAY_NAME"
    JSON_STRING = "JSON_STRING"


class MetadataDirection(StrEnum):
    OUTBOUND = "OUTBOUND"
    INBOUND = "INBOUND"
    BIDIRECTIONAL = "BIDIRECTIONAL"


class SyncDirection(StrEnum):
    OUTBOUND = "OUTBOUND"
    INBOUND = "INBOUND"
    BIDIRECTIONAL = "BIDIRECTIONAL"


class ConflictPolicy(StrEnum):
    MANUAL = "MANUAL"
    APPLICATION_WINS = "APPLICATION_WINS"
    SHAREPOINT_WINS = "SHAREPOINT_WINS"
    LATEST_MODIFIED_WINS = "LATEST_MODIFIED_WINS"
    CREATE_COPY = "CREATE_COPY"


class DeletePolicy(StrEnum):
    IGNORE_REMOTE_DELETE = "IGNORE_REMOTE_DELETE"
    ARCHIVE_LOCAL = "ARCHIVE_LOCAL"
    MARK_MISSING = "MARK_MISSING"
    DELETE_LOCAL_SOFT = "DELETE_LOCAL_SOFT"


class SyncJobType(StrEnum):
    MANUAL_FULL = "MANUAL_FULL"
    MANUAL_INCREMENTAL = "MANUAL_INCREMENTAL"
    SCHEDULED_FULL = "SCHEDULED_FULL"
    SCHEDULED_INCREMENTAL = "SCHEDULED_INCREMENTAL"
    WEBHOOK_INCREMENTAL = "WEBHOOK_INCREMENTAL"
    SINGLE_FILE_PUSH = "SINGLE_FILE_PUSH"
    SINGLE_FILE_PULL = "SINGLE_FILE_PULL"
    RECONCILIATION = "RECONCILIATION"


class SharePointSyncJobStatus(StrEnum):
    QUEUED = "QUEUED"
    AUTHENTICATING = "AUTHENTICATING"
    DISCOVERING = "DISCOVERING"
    COMPARING = "COMPARING"
    TRANSFERRING = "TRANSFERRING"
    UPDATING_METADATA = "UPDATING_METADATA"
    RESOLVING_CONFLICTS = "RESOLVING_CONFLICTS"
    PERSISTING = "PERSISTING"
    COMPLETED = "COMPLETED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    FAILED = "FAILED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    DEAD_LETTER = "DEAD_LETTER"


ACTIVE_SYNC_JOB_STATUSES = frozenset(
    {
        SharePointSyncJobStatus.QUEUED,
        SharePointSyncJobStatus.AUTHENTICATING,
        SharePointSyncJobStatus.DISCOVERING,
        SharePointSyncJobStatus.COMPARING,
        SharePointSyncJobStatus.TRANSFERRING,
        SharePointSyncJobStatus.UPDATING_METADATA,
        SharePointSyncJobStatus.RESOLVING_CONFLICTS,
        SharePointSyncJobStatus.PERSISTING,
        SharePointSyncJobStatus.CANCEL_REQUESTED,
    }
)


class SyncItemOperation(StrEnum):
    CREATE_REMOTE = "CREATE_REMOTE"
    UPDATE_REMOTE = "UPDATE_REMOTE"
    CREATE_LOCAL = "CREATE_LOCAL"
    UPDATE_LOCAL = "UPDATE_LOCAL"
    MOVE_REMOTE = "MOVE_REMOTE"
    RENAME_REMOTE = "RENAME_REMOTE"
    UPDATE_REMOTE_METADATA = "UPDATE_REMOTE_METADATA"
    UPDATE_LOCAL_METADATA = "UPDATE_LOCAL_METADATA"
    REMOTE_DELETE_DETECTED = "REMOTE_DELETE_DETECTED"
    LOCAL_DELETE_DETECTED = "LOCAL_DELETE_DETECTED"
    SKIP = "SKIP"
    CONFLICT = "CONFLICT"


class SyncItemStatus(StrEnum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    CONFLICT = "CONFLICT"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    DEAD_LETTER = "DEAD_LETTER"


class GraphSubscriptionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRING = "EXPIRING"
    EXPIRED = "EXPIRED"
    RENEWAL_FAILED = "RENEWAL_FAILED"
    DISABLED = "DISABLED"
    DELETED = "DELETED"


class GraphWebhookProcessingStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATED = "VALIDATED"
    QUEUED = "QUEUED"
    PROCESSED = "PROCESSED"
    IGNORED = "IGNORED"
    FAILED = "FAILED"
    DUPLICATE = "DUPLICATE"


class SyncConflictType(StrEnum):
    BOTH_MODIFIED = "BOTH_MODIFIED"
    LOCAL_DELETED_REMOTE_MODIFIED = "LOCAL_DELETED_REMOTE_MODIFIED"
    REMOTE_DELETED_LOCAL_MODIFIED = "REMOTE_DELETED_LOCAL_MODIFIED"
    METADATA_CONFLICT = "METADATA_CONFLICT"
    PATH_CONFLICT = "PATH_CONFLICT"
    DUPLICATE_REMOTE_ITEM = "DUPLICATE_REMOTE_ITEM"
    HASH_MISMATCH = "HASH_MISMATCH"
    VERSION_MISMATCH = "VERSION_MISMATCH"


class SyncConflictStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class SyncConflictResolution(StrEnum):
    KEEP_LOCAL = "KEEP_LOCAL"
    KEEP_REMOTE = "KEEP_REMOTE"
    KEEP_BOTH = "KEEP_BOTH"
    MERGE_METADATA = "MERGE_METADATA"
    IGNORE_REMOTE_CHANGE = "IGNORE_REMOTE_CHANGE"
    IGNORE_LOCAL_CHANGE = "IGNORE_LOCAL_CHANGE"


class DeadLetterStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RETRY_QUEUED = "RETRY_QUEUED"
    RETRIED = "RETRIED"
    DISMISSED = "DISMISSED"
