"""phase10 sharepoint production

Revision ID: 20260726_0010
Revises: 20260726_0009
Create Date: 2026-07-26 03:04:18.534196
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260726_0010"
down_revision: str | Sequence[str] | None = "20260726_0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PHASE10_AUDIT_ACTIONS = (
    "CREATE_SHAREPOINT_CONNECTION",
    "UPDATE_SHAREPOINT_CONNECTION",
    "TEST_SHAREPOINT_CONNECTION",
    "DISABLE_SHAREPOINT_CONNECTION",
    "CREATE_FOLDER_MAPPING",
    "UPDATE_FOLDER_MAPPING",
    "CREATE_METADATA_MAPPING",
    "UPDATE_METADATA_MAPPING",
    "CREATE_SYNC_PROFILE",
    "UPDATE_SYNC_PROFILE",
    "ACTIVATE_SYNC_PROFILE",
    "DEACTIVATE_SYNC_PROFILE",
    "QUEUE_SHAREPOINT_SYNC",
    "START_SHAREPOINT_SYNC",
    "COMPLETE_SHAREPOINT_SYNC",
    "PARTIAL_SHAREPOINT_SYNC",
    "FAIL_SHAREPOINT_SYNC",
    "CANCEL_SHAREPOINT_SYNC",
    "RETRY_SHAREPOINT_SYNC",
    "RESET_SHAREPOINT_DELTA",
    "PUSH_FILE_TO_SHAREPOINT",
    "PULL_FILE_FROM_SHAREPOINT",
    "COPY_SHAREPOINT_FILE",
    "MOVE_SHAREPOINT_FILE",
    "RENAME_SHAREPOINT_FILE",
    "CREATE_SHAREPOINT_CONFLICT",
    "ASSIGN_SHAREPOINT_CONFLICT",
    "RESOLVE_SHAREPOINT_CONFLICT",
    "IGNORE_SHAREPOINT_CONFLICT",
    "CREATE_GRAPH_SUBSCRIPTION",
    "RENEW_GRAPH_SUBSCRIPTION",
    "FAIL_GRAPH_SUBSCRIPTION_RENEWAL",
    "DELETE_GRAPH_SUBSCRIPTION",
    "CREATE_NOTIFICATION_TEMPLATE",
    "UPDATE_NOTIFICATION_TEMPLATE",
    "CREATE_NOTIFICATION_RULE",
    "UPDATE_NOTIFICATION_RULE",
    "SEND_NOTIFICATION",
    "FAIL_NOTIFICATION",
    "RETRY_NOTIFICATION",
    "CREATE_RETENTION_POLICY",
    "UPDATE_RETENTION_POLICY",
    "EXECUTE_RETENTION_CLEANUP",
    "ROTATE_ENCRYPTION_KEY",
    "GENERATE_BACKUP",
    "RESTORE_BACKUP",
)

PHASE10_ENUM_TYPES = (
    "dead_letter_status",
    "graph_subscription_status",
    "graph_webhook_processing_status",
    "notification_channel",
    "notification_content_type",
    "notification_delivery_status",
    "notification_digest_mode",
    "notification_event_type",
    "notification_recipient_type",
    "notification_scope_type",
    "notification_severity",
    "retention_entity_type",
    "retention_scope_type",
    "sharepoint_auth_mode",
    "sharepoint_conflict_policy",
    "sharepoint_connection_status",
    "sharepoint_delete_policy",
    "sharepoint_folder_mapping_scope",
    "sharepoint_metadata_data_type",
    "sharepoint_metadata_direction",
    "sharepoint_sync_conflict_resolution",
    "sharepoint_sync_conflict_status",
    "sharepoint_sync_conflict_type",
    "sharepoint_sync_direction",
    "sharepoint_sync_item_operation",
    "sharepoint_sync_item_status",
    "sharepoint_sync_job_direction",
    "sharepoint_sync_job_status",
    "sharepoint_sync_job_type",
    "sharepoint_sync_scope_type",
    "worker_heartbeat_state",
)


def _extend_postgresql_enum(name: str, values: tuple[str, ...]) -> None:
    """Append stable values without exposing them to non-PostgreSQL dialects."""

    if op.get_bind().dialect.name != "postgresql":
        return
    for value in values:
        op.execute(sa.text(f"ALTER TYPE {name} ADD VALUE IF NOT EXISTS '{value}'"))


def _drop_phase10_enum_types() -> None:
    """Drop types owned exclusively by this revision after dependent tables."""

    if op.get_bind().dialect.name != "postgresql":
        return
    for name in reversed(PHASE10_ENUM_TYPES):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {name}"))


def upgrade() -> None:
    """Apply schema changes."""
    _extend_postgresql_enum("audit_action", PHASE10_AUDIT_ACTIONS)
    _extend_postgresql_enum(
        "document_file_status",
        ("PENDING_SCAN", "SCAN_FAILED"),
    )
    # Revision 0009 has no table that depends on Phase 10-owned enum types.
    # This also repairs remnants left by an interrupted early downgrade.
    _drop_phase10_enum_types()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_heartbeats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("worker_name", sa.String(length=100), nullable=False),
        sa.Column("worker_instance", sa.String(length=255), nullable=False),
        sa.Column("queue_name", sa.String(length=100), nullable=False),
        sa.Column(
            "state",
            sa.Enum("ACTIVE", "DRAINING", "STOPPED", name="worker_heartbeat_state"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_heartbeats")),
        sa.UniqueConstraint(
            "worker_name", "worker_instance", name="uq_worker_heartbeats_name_instance"
        ),
    )
    op.create_index(
        "ix_worker_heartbeats_last_heartbeat_at",
        "worker_heartbeats",
        ["last_heartbeat_at"],
        unique=False,
    )
    op.create_index(
        "ix_worker_heartbeats_queue_name",
        "worker_heartbeats",
        ["queue_name"],
        unique=False,
    )
    op.create_index(
        "ix_worker_heartbeats_worker_name",
        "worker_heartbeats",
        ["worker_name"],
        unique=False,
    )
    op.create_table(
        "dead_letter_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_name", sa.String(length=500), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("maximum_attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column(
            "first_failed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_failed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "retry_history_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "sanitized_arguments_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "RETRY_QUEUED",
                "RETRIED",
                "DISMISSED",
                name="dead_letter_status",
            ),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("dismissed_by", sa.Uuid(), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissal_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dismissed_by"],
            ["users.id"],
            name=op.f("fk_dead_letter_jobs_dismissed_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dead_letter_jobs")),
    )
    op.create_index(
        "ix_dead_letter_jobs_last_failed",
        "dead_letter_jobs",
        ["last_failed_at"],
        unique=False,
    )
    op.create_index(
        "ix_dead_letter_jobs_status", "dead_letter_jobs", ["status"], unique=False
    )
    op.create_index(
        "ix_dead_letter_jobs_task_name", "dead_letter_jobs", ["task_name"], unique=False
    )
    op.create_table(
        "in_app_notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "DOCUMENT_UPLOADED",
                "DOCUMENT_REPLACED",
                "DOCUMENT_REVISION_CREATED",
                "EXTRACTION_COMPLETED",
                "EXTRACTION_FAILED",
                "OCR_COMPLETED",
                "OCR_FAILED",
                "LANGUAGE_DETECTION_COMPLETED",
                "COMPLIANCE_VALIDATION_COMPLETED",
                "COMPLIANCE_VALIDATION_FAILED",
                "SIMILARITY_COMPLETED",
                "GLOSSARY_VALIDATION_COMPLETED",
                "CRITICAL_FINDING_CREATED",
                "MAJOR_FINDING_CREATED",
                "FINDING_ASSIGNED",
                "FINDING_RESOLVED",
                "FINDING_REOPENED",
                "ACCEPTED_RISK_EXPIRING",
                "SHAREPOINT_SYNC_COMPLETED",
                "SHAREPOINT_SYNC_PARTIAL",
                "SHAREPOINT_SYNC_FAILED",
                "SHAREPOINT_CONFLICT_CREATED",
                "SHAREPOINT_CONNECTION_FAILED",
                "GRAPH_SUBSCRIPTION_RENEWAL_FAILED",
                "REPORT_GENERATED",
                "REPORT_FAILED",
                "SYSTEM_BACKUP_FAILED",
                "SYSTEM_DISK_SPACE_LOW",
                "SYSTEM_WORKER_UNAVAILABLE",
                "SYSTEM_SECURITY_ALERT",
                name="notification_event_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFORMATION",
                "WARNING",
                "ERROR",
                "CRITICAL",
                name="notification_severity",
            ),
            server_default="INFORMATION",
            nullable=False,
        ),
        sa.Column("related_entity_type", sa.String(length=100), nullable=True),
        sa.Column("related_entity_id", sa.Uuid(), nullable=True),
        sa.Column("action_url", sa.String(length=2000), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_in_app_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_in_app_notifications")),
    )
    op.create_index(
        "ix_in_app_notifications_created_at",
        "in_app_notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_in_app_notifications_event_type",
        "in_app_notifications",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        "ix_in_app_notifications_expires_at",
        "in_app_notifications",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_in_app_notifications_is_read",
        "in_app_notifications",
        ["is_read"],
        unique=False,
    )
    op.create_index(
        "ix_in_app_notifications_user_id",
        "in_app_notifications",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_in_app_notifications_user_unread",
        "in_app_notifications",
        ["user_id", "is_read", "dismissed_at"],
        unique=False,
    )
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "DOCUMENT_UPLOADED",
                "DOCUMENT_REPLACED",
                "DOCUMENT_REVISION_CREATED",
                "EXTRACTION_COMPLETED",
                "EXTRACTION_FAILED",
                "OCR_COMPLETED",
                "OCR_FAILED",
                "LANGUAGE_DETECTION_COMPLETED",
                "COMPLIANCE_VALIDATION_COMPLETED",
                "COMPLIANCE_VALIDATION_FAILED",
                "SIMILARITY_COMPLETED",
                "GLOSSARY_VALIDATION_COMPLETED",
                "CRITICAL_FINDING_CREATED",
                "MAJOR_FINDING_CREATED",
                "FINDING_ASSIGNED",
                "FINDING_RESOLVED",
                "FINDING_REOPENED",
                "ACCEPTED_RISK_EXPIRING",
                "SHAREPOINT_SYNC_COMPLETED",
                "SHAREPOINT_SYNC_PARTIAL",
                "SHAREPOINT_SYNC_FAILED",
                "SHAREPOINT_CONFLICT_CREATED",
                "SHAREPOINT_CONNECTION_FAILED",
                "GRAPH_SUBSCRIPTION_RENEWAL_FAILED",
                "REPORT_GENERATED",
                "REPORT_FAILED",
                "SYSTEM_BACKUP_FAILED",
                "SYSTEM_DISK_SPACE_LOW",
                "SYSTEM_WORKER_UNAVAILABLE",
                "SYSTEM_SECURITY_ALERT",
                name="notification_event_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "in_app_enabled", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "email_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "teams_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "telegram_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "digest_mode",
            sa.Enum("NONE", "DAILY", "WEEKLY", name="notification_digest_mode"),
            server_default="NONE",
            nullable=False,
        ),
        sa.Column(
            "quiet_hours_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column(
            "timezone", sa.String(length=100), server_default="UTC", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint(
            "user_id", "event_type", name="uq_notification_preferences_user_event"
        ),
    )
    op.create_index(
        "ix_notification_preferences_event_type",
        "notification_preferences",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        "ix_notification_preferences_user_id",
        "notification_preferences",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "notification_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "DOCUMENT_UPLOADED",
                "DOCUMENT_REPLACED",
                "DOCUMENT_REVISION_CREATED",
                "EXTRACTION_COMPLETED",
                "EXTRACTION_FAILED",
                "OCR_COMPLETED",
                "OCR_FAILED",
                "LANGUAGE_DETECTION_COMPLETED",
                "COMPLIANCE_VALIDATION_COMPLETED",
                "COMPLIANCE_VALIDATION_FAILED",
                "SIMILARITY_COMPLETED",
                "GLOSSARY_VALIDATION_COMPLETED",
                "CRITICAL_FINDING_CREATED",
                "MAJOR_FINDING_CREATED",
                "FINDING_ASSIGNED",
                "FINDING_RESOLVED",
                "FINDING_REOPENED",
                "ACCEPTED_RISK_EXPIRING",
                "SHAREPOINT_SYNC_COMPLETED",
                "SHAREPOINT_SYNC_PARTIAL",
                "SHAREPOINT_SYNC_FAILED",
                "SHAREPOINT_CONFLICT_CREATED",
                "SHAREPOINT_CONNECTION_FAILED",
                "GRAPH_SUBSCRIPTION_RENEWAL_FAILED",
                "REPORT_GENERATED",
                "REPORT_FAILED",
                "SYSTEM_BACKUP_FAILED",
                "SYSTEM_DISK_SPACE_LOW",
                "SYSTEM_WORKER_UNAVAILABLE",
                "SYSTEM_SECURITY_ALERT",
                name="notification_event_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "IN_APP",
                "EMAIL_GRAPH",
                "TEAMS",
                "TELEGRAM",
                name="notification_channel",
            ),
            nullable=False,
        ),
        sa.Column("subject_template", sa.String(length=500), nullable=True),
        sa.Column("body_template", sa.Text(), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum(
                "PLAIN_TEXT",
                "HTML",
                "MARKDOWN",
                "JSON_CARD",
                name="notification_content_type",
            ),
            server_default="PLAIN_TEXT",
            nullable=False,
        ),
        sa.Column(
            "language_code", sa.String(length=10), server_default="en", nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version >= 1",
            name=op.f(
                "ck_notification_templates_notification_templates_version_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_notification_templates_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_notification_templates_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_templates")),
        sa.UniqueConstraint(
            "code",
            "version",
            "channel",
            "language_code",
            name="uq_notification_templates_code_version_channel_language",
        ),
    )
    op.create_index(
        "ix_notification_templates_channel",
        "notification_templates",
        ["channel"],
        unique=False,
    )
    op.create_index(
        "ix_notification_templates_event_type",
        "notification_templates",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        "ix_notification_templates_is_active",
        "notification_templates",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_notification_templates_resolution",
        "notification_templates",
        ["event_type", "channel", "language_code", "is_default", "is_active"],
        unique=False,
    )
    op.create_table(
        "sharepoint_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tenant_id_reference", sa.String(length=255), nullable=False),
        sa.Column("site_hostname", sa.String(length=255), nullable=False),
        sa.Column("site_path", sa.String(length=1000), nullable=False),
        sa.Column("site_id", sa.String(length=1000), nullable=True),
        sa.Column("drive_id", sa.String(length=1000), nullable=True),
        sa.Column("library_name", sa.String(length=255), nullable=False),
        sa.Column(
            "root_folder_path",
            sa.String(length=1000),
            server_default="DocumentCompliance",
            nullable=False,
        ),
        sa.Column(
            "auth_mode",
            sa.Enum("CLIENT_SECRET", "CERTIFICATE", name="sharepoint_auth_mode"),
            server_default="CLIENT_SECRET",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_CONFIGURED",
                "CONNECTED",
                "DEGRADED",
                "AUTHENTICATION_FAILED",
                "PERMISSION_DENIED",
                "UNAVAILABLE",
                "DISABLED",
                name="sharepoint_connection_status",
            ),
            server_default="NOT_CONFIGURED",
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_test_status", sa.String(length=100), nullable=True),
        sa.Column("last_test_message", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_sharepoint_connections_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_sharepoint_connections_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharepoint_connections")),
        sa.UniqueConstraint("name", name=op.f("uq_sharepoint_connections_name")),
    )
    op.create_index(
        "ix_sharepoint_connections_active",
        "sharepoint_connections",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_connections_status",
        "sharepoint_connections",
        ["status"],
        unique=False,
    )
    op.create_index(
        "uq_sharepoint_connections_default",
        "sharepoint_connections",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default IS TRUE AND is_active IS TRUE"),
        sqlite_where=sa.text("is_default = 1 AND is_active = 1"),
    )
    op.create_table(
        "data_retention_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "TEMP_UPLOAD",
                "REPORT_SNAPSHOT",
                "JOB_LOG",
                "NOTIFICATION",
                "AUDIT_LOG",
                "DELETED_FILE",
                "EXTRACTION_HISTORY",
                "OCR_HISTORY",
                "SYNC_HISTORY",
                "WEBHOOK_EVENT",
                name="retention_entity_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "scope_type",
            sa.Enum(
                "GLOBAL",
                "DEPARTMENT",
                "DOCUMENT_TYPE",
                "DEPARTMENT_DOCUMENT_TYPE",
                name="retention_scope_type",
            ),
            server_default="GLOBAL",
            nullable=False,
        ),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("document_type_id", sa.Uuid(), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("archive_after_days", sa.Integer(), nullable=True),
        sa.Column("delete_after_days", sa.Integer(), nullable=True),
        sa.Column(
            "legal_hold_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope_type = 'GLOBAL' AND department_id IS NULL AND document_type_id IS NULL) OR (scope_type = 'DEPARTMENT' AND department_id IS NOT NULL AND document_type_id IS NULL) OR (scope_type = 'DOCUMENT_TYPE' AND department_id IS NULL AND document_type_id IS NOT NULL) OR (scope_type = 'DEPARTMENT_DOCUMENT_TYPE' AND department_id IS NOT NULL AND document_type_id IS NOT NULL)",
            name=op.f(
                "ck_data_retention_policies_data_retention_policies_scope_consistent"
            ),
        ),
        sa.CheckConstraint(
            "retention_days >= 1 AND (archive_after_days IS NULL OR archive_after_days >= 1) AND (delete_after_days IS NULL OR delete_after_days >= 1) AND (archive_after_days IS NULL OR delete_after_days IS NULL OR delete_after_days >= archive_after_days)",
            name=op.f("ck_data_retention_policies_data_retention_policies_day_ranges"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_data_retention_policies_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_data_retention_policies_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_data_retention_policies_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_data_retention_policies_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_retention_policies")),
    )
    op.create_index(
        "ix_data_retention_policies_department_id",
        "data_retention_policies",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        "ix_data_retention_policies_document_type_id",
        "data_retention_policies",
        ["document_type_id"],
        unique=False,
    )
    op.create_index(
        "ix_data_retention_policies_entity_type",
        "data_retention_policies",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        "ix_data_retention_policies_is_active",
        "data_retention_policies",
        ["is_active"],
        unique=False,
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "DOCUMENT_UPLOADED",
                "DOCUMENT_REPLACED",
                "DOCUMENT_REVISION_CREATED",
                "EXTRACTION_COMPLETED",
                "EXTRACTION_FAILED",
                "OCR_COMPLETED",
                "OCR_FAILED",
                "LANGUAGE_DETECTION_COMPLETED",
                "COMPLIANCE_VALIDATION_COMPLETED",
                "COMPLIANCE_VALIDATION_FAILED",
                "SIMILARITY_COMPLETED",
                "GLOSSARY_VALIDATION_COMPLETED",
                "CRITICAL_FINDING_CREATED",
                "MAJOR_FINDING_CREATED",
                "FINDING_ASSIGNED",
                "FINDING_RESOLVED",
                "FINDING_REOPENED",
                "ACCEPTED_RISK_EXPIRING",
                "SHAREPOINT_SYNC_COMPLETED",
                "SHAREPOINT_SYNC_PARTIAL",
                "SHAREPOINT_SYNC_FAILED",
                "SHAREPOINT_CONFLICT_CREATED",
                "SHAREPOINT_CONNECTION_FAILED",
                "GRAPH_SUBSCRIPTION_RENEWAL_FAILED",
                "REPORT_GENERATED",
                "REPORT_FAILED",
                "SYSTEM_BACKUP_FAILED",
                "SYSTEM_DISK_SPACE_LOW",
                "SYSTEM_WORKER_UNAVAILABLE",
                "SYSTEM_SECURITY_ALERT",
                name="notification_event_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "IN_APP",
                "EMAIL_GRAPH",
                "TEAMS",
                "TELEGRAM",
                name="notification_channel",
            ),
            nullable=False,
        ),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column(
            "recipient_type",
            sa.Enum(
                "EVENT_ACTOR",
                "DOCUMENT_OWNER",
                "DOCUMENT_CONTROLLER",
                "DEPARTMENT_USERS",
                "ROLE",
                "SPECIFIC_USERS",
                "SPECIFIC_EMAILS",
                "TEAMS_CHANNEL",
                "TELEGRAM_CHAT",
                name="notification_recipient_type",
            ),
            nullable=False,
        ),
        sa.Column("recipient_reference", sa.String(length=1000), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "SENDING",
                "SENT",
                "DELIVERED",
                "FAILED",
                "RETRY_SCHEDULED",
                "CANCELLED",
                "SKIPPED",
                name="notification_delivery_status",
            ),
            server_default="QUEUED",
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("maximum_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("provider_message_id", sa.String(length=1000), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND maximum_attempts >= 1 AND attempt_count <= maximum_attempts",
            name=op.f(
                "ck_notification_deliveries_notification_deliveries_attempt_range"
            ),
        ),
        sa.CheckConstraint(
            "length(payload_hash) = 64",
            name=op.f(
                "ck_notification_deliveries_notification_deliveries_payload_hash_length"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["notification_templates.id"],
            name=op.f("fk_notification_deliveries_template_id_notification_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
    )
    op.create_index(
        "ix_notification_deliveries_channel",
        "notification_deliveries",
        ["channel"],
        unique=False,
    )
    op.create_index(
        "ix_notification_deliveries_created_at",
        "notification_deliveries",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_deliveries_event_type",
        "notification_deliveries",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        "ix_notification_deliveries_next_retry_at",
        "notification_deliveries",
        ["next_retry_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_deliveries_retry_queue",
        "notification_deliveries",
        ["status", "next_retry_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_deliveries_status",
        "notification_deliveries",
        ["status"],
        unique=False,
    )
    op.create_table(
        "notification_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "DOCUMENT_UPLOADED",
                "DOCUMENT_REPLACED",
                "DOCUMENT_REVISION_CREATED",
                "EXTRACTION_COMPLETED",
                "EXTRACTION_FAILED",
                "OCR_COMPLETED",
                "OCR_FAILED",
                "LANGUAGE_DETECTION_COMPLETED",
                "COMPLIANCE_VALIDATION_COMPLETED",
                "COMPLIANCE_VALIDATION_FAILED",
                "SIMILARITY_COMPLETED",
                "GLOSSARY_VALIDATION_COMPLETED",
                "CRITICAL_FINDING_CREATED",
                "MAJOR_FINDING_CREATED",
                "FINDING_ASSIGNED",
                "FINDING_RESOLVED",
                "FINDING_REOPENED",
                "ACCEPTED_RISK_EXPIRING",
                "SHAREPOINT_SYNC_COMPLETED",
                "SHAREPOINT_SYNC_PARTIAL",
                "SHAREPOINT_SYNC_FAILED",
                "SHAREPOINT_CONFLICT_CREATED",
                "SHAREPOINT_CONNECTION_FAILED",
                "GRAPH_SUBSCRIPTION_RENEWAL_FAILED",
                "REPORT_GENERATED",
                "REPORT_FAILED",
                "SYSTEM_BACKUP_FAILED",
                "SYSTEM_DISK_SPACE_LOW",
                "SYSTEM_WORKER_UNAVAILABLE",
                "SYSTEM_SECURITY_ALERT",
                name="notification_event_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "IN_APP",
                "EMAIL_GRAPH",
                "TEAMS",
                "TELEGRAM",
                name="notification_channel",
            ),
            nullable=False,
        ),
        sa.Column(
            "scope_type",
            sa.Enum(
                "GLOBAL",
                "DEPARTMENT",
                "DOCUMENT_TYPE",
                "DEPARTMENT_DOCUMENT_TYPE",
                name="notification_scope_type",
            ),
            server_default="GLOBAL",
            nullable=False,
        ),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("document_type_id", sa.Uuid(), nullable=True),
        sa.Column(
            "severity_filter_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "recipient_type",
            sa.Enum(
                "EVENT_ACTOR",
                "DOCUMENT_OWNER",
                "DOCUMENT_CONTROLLER",
                "DEPARTMENT_USERS",
                "ROLE",
                "SPECIFIC_USERS",
                "SPECIFIC_EMAILS",
                "TEAMS_CHANNEL",
                "TELEGRAM_CHAT",
                name="notification_recipient_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "recipient_value_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column(
            "send_immediately", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "digest_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("digest_schedule", sa.String(length=200), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope_type = 'GLOBAL' AND department_id IS NULL AND document_type_id IS NULL) OR (scope_type = 'DEPARTMENT' AND department_id IS NOT NULL AND document_type_id IS NULL) OR (scope_type = 'DOCUMENT_TYPE' AND department_id IS NULL AND document_type_id IS NOT NULL) OR (scope_type = 'DEPARTMENT_DOCUMENT_TYPE' AND department_id IS NOT NULL AND document_type_id IS NOT NULL)",
            name=op.f("ck_notification_rules_notification_rules_scope_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_notification_rules_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_notification_rules_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_notification_rules_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["notification_templates.id"],
            name=op.f("fk_notification_rules_template_id_notification_templates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_notification_rules_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_rules")),
    )
    op.create_index(
        "ix_notification_rules_channel", "notification_rules", ["channel"], unique=False
    )
    op.create_index(
        "ix_notification_rules_department_id",
        "notification_rules",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_rules_document_type_id",
        "notification_rules",
        ["document_type_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_rules_event_type",
        "notification_rules",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        "ix_notification_rules_is_active",
        "notification_rules",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_notification_rules_resolution",
        "notification_rules",
        ["event_type", "department_id", "document_type_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "sharepoint_metadata_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sharepoint_connection_id", sa.Uuid(), nullable=False),
        sa.Column("document_field", sa.String(length=255), nullable=False),
        sa.Column(
            "sharepoint_field_internal_name", sa.String(length=255), nullable=False
        ),
        sa.Column(
            "data_type",
            sa.Enum(
                "STRING",
                "INTEGER",
                "BOOLEAN",
                "DATE",
                "DATETIME",
                "CHOICE",
                "LOOKUP_TEXT",
                "USER_DISPLAY_NAME",
                "JSON_STRING",
                name="sharepoint_metadata_data_type",
            ),
            server_default="STRING",
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.Enum(
                "OUTBOUND",
                "INBOUND",
                "BIDIRECTIONAL",
                name="sharepoint_metadata_direction",
            ),
            server_default="OUTBOUND",
            nullable=False,
        ),
        sa.Column("is_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "default_value",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("transformer_code", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sharepoint_connection_id"],
            ["sharepoint_connections.id"],
            name=op.f(
                "fk_sharepoint_metadata_mappings_sharepoint_connection_id_sharepoint_connections"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharepoint_metadata_mappings")),
        sa.UniqueConstraint(
            "sharepoint_connection_id",
            "document_field",
            "sharepoint_field_internal_name",
            name="uq_sharepoint_metadata_mapping_fields",
        ),
    )
    op.create_index(
        "ix_sharepoint_metadata_mappings_active",
        "sharepoint_metadata_mappings",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_metadata_mappings_connection",
        "sharepoint_metadata_mappings",
        ["sharepoint_connection_id"],
        unique=False,
    )
    op.create_table(
        "sharepoint_folder_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sharepoint_connection_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("document_type_id", sa.Uuid(), nullable=True),
        sa.Column(
            "mapping_scope",
            sa.Enum(
                "GLOBAL",
                "DEPARTMENT",
                "SECTION",
                "DOCUMENT_TYPE",
                "DEPARTMENT_DOCUMENT_TYPE",
                "SECTION_DOCUMENT_TYPE",
                name="sharepoint_folder_mapping_scope",
            ),
            nullable=False,
        ),
        sa.Column("remote_folder_path", sa.String(length=1000), nullable=False),
        sa.Column("remote_folder_id", sa.String(length=1000), nullable=True),
        sa.Column("filename_pattern", sa.String(length=500), nullable=True),
        sa.Column(
            "create_folder_if_missing",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority >= 0",
            name=op.f(
                "ck_sharepoint_folder_mappings_sharepoint_folder_mappings_priority_nonnegative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_sharepoint_folder_mappings_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_sharepoint_folder_mappings_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_sharepoint_folder_mappings_document_type_id_document_types"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_sharepoint_folder_mappings_section_id_sections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sharepoint_connection_id"],
            ["sharepoint_connections.id"],
            name=op.f(
                "fk_sharepoint_folder_mappings_sharepoint_connection_id_sharepoint_connections"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_sharepoint_folder_mappings_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharepoint_folder_mappings")),
    )
    op.create_index(
        "ix_sharepoint_folder_mappings_connection",
        "sharepoint_folder_mappings",
        ["sharepoint_connection_id"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_folder_mappings_resolution",
        "sharepoint_folder_mappings",
        [
            "sharepoint_connection_id",
            "mapping_scope",
            "department_id",
            "section_id",
            "document_type_id",
            "priority",
        ],
        unique=False,
    )
    op.create_table(
        "sharepoint_sync_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sharepoint_connection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "OUTBOUND", "INBOUND", "BIDIRECTIONAL", name="sharepoint_sync_direction"
            ),
            server_default="OUTBOUND",
            nullable=False,
        ),
        sa.Column(
            "scope_type",
            sa.Enum(
                "GLOBAL",
                "DEPARTMENT",
                "SECTION",
                "DOCUMENT_TYPE",
                "DEPARTMENT_DOCUMENT_TYPE",
                "SECTION_DOCUMENT_TYPE",
                name="sharepoint_sync_scope_type",
            ),
            server_default="GLOBAL",
            nullable=False,
        ),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("document_type_id", sa.Uuid(), nullable=True),
        sa.Column("folder_mapping_id", sa.Uuid(), nullable=True),
        sa.Column(
            "metadata_mapping_profile",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "conflict_policy",
            sa.Enum(
                "MANUAL",
                "APPLICATION_WINS",
                "SHAREPOINT_WINS",
                "LATEST_MODIFIED_WINS",
                "CREATE_COPY",
                name="sharepoint_conflict_policy",
            ),
            server_default="MANUAL",
            nullable=False,
        ),
        sa.Column(
            "delete_policy",
            sa.Enum(
                "IGNORE_REMOTE_DELETE",
                "ARCHIVE_LOCAL",
                "MARK_MISSING",
                "DELETE_LOCAL_SOFT",
                name="sharepoint_delete_policy",
            ),
            server_default="IGNORE_REMOTE_DELETE",
            nullable=False,
        ),
        sa.Column("sync_schedule", sa.String(length=255), nullable=True),
        sa.Column(
            "delta_sync_enabled", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "webhook_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_sharepoint_sync_profiles_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_sharepoint_sync_profiles_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_sharepoint_sync_profiles_document_type_id_document_types"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["folder_mapping_id"],
            ["sharepoint_folder_mappings.id"],
            name=op.f(
                "fk_sharepoint_sync_profiles_folder_mapping_id_sharepoint_folder_mappings"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_sharepoint_sync_profiles_section_id_sections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sharepoint_connection_id"],
            ["sharepoint_connections.id"],
            name=op.f(
                "fk_sharepoint_sync_profiles_sharepoint_connection_id_sharepoint_connections"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_sharepoint_sync_profiles_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharepoint_sync_profiles")),
        sa.UniqueConstraint("name", name=op.f("uq_sharepoint_sync_profiles_name")),
    )
    op.create_index(
        "ix_sharepoint_sync_profiles_active",
        "sharepoint_sync_profiles",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_profiles_connection",
        "sharepoint_sync_profiles",
        ["sharepoint_connection_id"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_profiles_scope",
        "sharepoint_sync_profiles",
        ["scope_type", "department_id", "section_id", "document_type_id"],
        unique=False,
    )
    op.create_table(
        "graph_subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sharepoint_connection_id", sa.Uuid(), nullable=False),
        sa.Column("sync_profile_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.String(length=1000), nullable=False),
        sa.Column("resource", sa.String(length=2000), nullable=False),
        sa.Column("change_type", sa.String(length=100), nullable=False),
        sa.Column("notification_url", sa.String(length=2000), nullable=False),
        sa.Column("lifecycle_notification_url", sa.String(length=2000), nullable=True),
        sa.Column("client_state_hash", sa.String(length=64), nullable=False),
        sa.Column("expiration_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "EXPIRING",
                "EXPIRED",
                "RENEWAL_FAILED",
                "DISABLED",
                "DELETED",
                name="graph_subscription_status",
            ),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("last_renewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_notification_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("renewal_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(client_state_hash) = 64",
            name=op.f(
                "ck_graph_subscriptions_graph_subscriptions_client_state_hash_length"
            ),
        ),
        sa.CheckConstraint(
            "renewal_attempts >= 0",
            name=op.f(
                "ck_graph_subscriptions_graph_subscriptions_renewal_attempts_nonnegative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["sharepoint_connection_id"],
            ["sharepoint_connections.id"],
            name=op.f(
                "fk_graph_subscriptions_sharepoint_connection_id_sharepoint_connections"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sync_profile_id"],
            ["sharepoint_sync_profiles.id"],
            name=op.f(
                "fk_graph_subscriptions_sync_profile_id_sharepoint_sync_profiles"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_subscriptions")),
        sa.UniqueConstraint(
            "sharepoint_connection_id",
            "sync_profile_id",
            "resource",
            name="uq_graph_subscriptions_resource_scope",
        ),
        sa.UniqueConstraint(
            "subscription_id", name="uq_graph_subscriptions_subscription_id"
        ),
    )
    op.create_index(
        "ix_graph_subscriptions_expiration",
        "graph_subscriptions",
        ["expiration_datetime"],
        unique=False,
    )
    op.create_index(
        "ix_graph_subscriptions_status", "graph_subscriptions", ["status"], unique=False
    )
    op.create_table(
        "sharepoint_sync_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sync_profile_id", sa.Uuid(), nullable=False),
        sa.Column("sharepoint_connection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum(
                "MANUAL_FULL",
                "MANUAL_INCREMENTAL",
                "SCHEDULED_FULL",
                "SCHEDULED_INCREMENTAL",
                "WEBHOOK_INCREMENTAL",
                "SINGLE_FILE_PUSH",
                "SINGLE_FILE_PULL",
                "RECONCILIATION",
                name="sharepoint_sync_job_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.Enum(
                "OUTBOUND",
                "INBOUND",
                "BIDIRECTIONAL",
                name="sharepoint_sync_job_direction",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "AUTHENTICATING",
                "DISCOVERING",
                "COMPARING",
                "TRANSFERRING",
                "UPDATING_METADATA",
                "RESOLVING_CONFLICTS",
                "PERSISTING",
                "COMPLETED",
                "PARTIALLY_COMPLETED",
                "FAILED",
                "CANCEL_REQUESTED",
                "CANCELLED",
                "DEAD_LETTER",
                name="sharepoint_sync_job_status",
            ),
            server_default="QUEUED",
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("current_stage", sa.String(length=500), nullable=True),
        sa.Column(
            "scope_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("maximum_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("delta_token_before", sa.String(length=64), nullable=True),
        sa.Column("delta_token_after", sa.String(length=64), nullable=True),
        sa.Column("items_discovered", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_processed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_created", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_updated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_skipped", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_conflicted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "result_summary_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_number >= 1 AND maximum_attempts >= 1 AND attempt_number <= maximum_attempts",
            name=op.f("ck_sharepoint_sync_jobs_sharepoint_sync_jobs_attempt_range"),
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100",
            name=op.f("ck_sharepoint_sync_jobs_sharepoint_sync_jobs_progress_range"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_sharepoint_sync_jobs_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sharepoint_connection_id"],
            ["sharepoint_connections.id"],
            name=op.f(
                "fk_sharepoint_sync_jobs_sharepoint_connection_id_sharepoint_connections"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_profile_id"],
            ["sharepoint_sync_profiles.id"],
            name=op.f(
                "fk_sharepoint_sync_jobs_sync_profile_id_sharepoint_sync_profiles"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharepoint_sync_jobs")),
    )
    op.create_index(
        "ix_sharepoint_sync_jobs_connection",
        "sharepoint_sync_jobs",
        ["sharepoint_connection_id"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_jobs_profile",
        "sharepoint_sync_jobs",
        ["sync_profile_id"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_jobs_requested_at",
        "sharepoint_sync_jobs",
        ["requested_at"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_jobs_status",
        "sharepoint_sync_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        "uq_sharepoint_sync_jobs_active_profile",
        "sharepoint_sync_jobs",
        ["sync_profile_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('COMPARING', 'TRANSFERRING', 'CANCEL_REQUESTED', 'PERSISTING', 'UPDATING_METADATA', 'QUEUED', 'DISCOVERING', 'AUTHENTICATING', 'RESOLVING_CONFLICTS')"
        ),
        sqlite_where=sa.text(
            "status IN ('COMPARING', 'TRANSFERRING', 'CANCEL_REQUESTED', 'PERSISTING', 'UPDATING_METADATA', 'QUEUED', 'DISCOVERING', 'AUTHENTICATING', 'RESOLVING_CONFLICTS')"
        ),
    )
    op.create_table(
        "graph_webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.String(length=1000), nullable=False),
        sa.Column("resource", sa.String(length=2000), nullable=False),
        sa.Column("change_type", sa.String(length=100), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=True),
        sa.Column(
            "client_state_valid", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "processing_status",
            sa.Enum(
                "RECEIVED",
                "VALIDATED",
                "QUEUED",
                "PROCESSED",
                "IGNORED",
                "FAILED",
                "DUPLICATE",
                name="graph_webhook_processing_status",
            ),
            server_default="RECEIVED",
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_job_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sync_job_id"],
            ["sharepoint_sync_jobs.id"],
            name=op.f("fk_graph_webhook_events_sync_job_id_sharepoint_sync_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_webhook_events")),
        sa.UniqueConstraint(
            "subscription_id", "payload_hash", name="uq_graph_webhook_event_payload"
        ),
    )
    op.create_index(
        "ix_graph_webhook_events_received",
        "graph_webhook_events",
        ["received_at"],
        unique=False,
    )
    op.create_index(
        "ix_graph_webhook_events_status",
        "graph_webhook_events",
        ["processing_status"],
        unique=False,
    )
    op.create_table(
        "sharepoint_delta_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sync_profile_id", sa.Uuid(), nullable=False),
        sa.Column("drive_id", sa.String(length=1000), nullable=False),
        sa.Column("folder_item_id", sa.String(length=1000), nullable=True),
        sa.Column("delta_link_encrypted", sa.Text(), nullable=False),
        sa.Column("delta_token_hash", sa.String(length=64), nullable=False),
        sa.Column("last_successful_sync_job_id", sa.Uuid(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_valid", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidation_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(delta_token_hash) = 64",
            name=op.f("ck_sharepoint_delta_states_sharepoint_delta_state_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["last_successful_sync_job_id"],
            ["sharepoint_sync_jobs.id"],
            name=op.f(
                "fk_sharepoint_delta_states_last_successful_sync_job_id_sharepoint_sync_jobs"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sync_profile_id"],
            ["sharepoint_sync_profiles.id"],
            name=op.f(
                "fk_sharepoint_delta_states_sync_profile_id_sharepoint_sync_profiles"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharepoint_delta_states")),
        sa.UniqueConstraint(
            "sync_profile_id",
            "drive_id",
            "folder_item_id",
            name="uq_sharepoint_delta_state_scope",
        ),
    )
    op.create_index(
        "ix_sharepoint_delta_states_synced_at",
        "sharepoint_delta_states",
        ["last_synced_at"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_delta_states_valid",
        "sharepoint_delta_states",
        ["is_valid"],
        unique=False,
    )
    op.create_table(
        "sharepoint_file_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_file_id", sa.Uuid(), nullable=False),
        sa.Column("remote_drive_id", sa.String(length=1000), nullable=False),
        sa.Column("remote_item_id", sa.String(length=1000), nullable=False),
        sa.Column("remote_version_id", sa.String(length=1000), nullable=False),
        sa.Column("remote_etag", sa.String(length=1000), nullable=True),
        sa.Column("remote_last_modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remote_last_modified_by", sa.String(length=500), nullable=True),
        sa.Column("remote_size", sa.BigInteger(), nullable=True),
        sa.Column("local_sha256_hash", sa.String(length=64), nullable=True),
        sa.Column("sync_job_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_file_id"],
            ["document_files.id"],
            name=op.f("fk_sharepoint_file_versions_document_file_id_document_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sync_job_id"],
            ["sharepoint_sync_jobs.id"],
            name=op.f("fk_sharepoint_file_versions_sync_job_id_sharepoint_sync_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharepoint_file_versions")),
        sa.UniqueConstraint(
            "document_file_id",
            "remote_drive_id",
            "remote_item_id",
            "remote_version_id",
            name="uq_sharepoint_file_remote_version",
        ),
    )
    op.create_index(
        "ix_sharepoint_file_versions_file",
        "sharepoint_file_versions",
        ["document_file_id"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_file_versions_remote",
        "sharepoint_file_versions",
        ["remote_drive_id", "remote_item_id"],
        unique=False,
    )
    op.create_table(
        "sharepoint_sync_conflicts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sync_job_id", sa.Uuid(), nullable=False),
        sa.Column("sync_item_id", sa.Uuid(), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("document_revision_id", sa.Uuid(), nullable=True),
        sa.Column("document_file_id", sa.Uuid(), nullable=True),
        sa.Column("remote_item_id", sa.String(length=1000), nullable=True),
        sa.Column(
            "conflict_type",
            sa.Enum(
                "BOTH_MODIFIED",
                "LOCAL_DELETED_REMOTE_MODIFIED",
                "REMOTE_DELETED_LOCAL_MODIFIED",
                "METADATA_CONFLICT",
                "PATH_CONFLICT",
                "DUPLICATE_REMOTE_ITEM",
                "HASH_MISMATCH",
                "VERSION_MISMATCH",
                name="sharepoint_sync_conflict_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_REVIEW",
                "RESOLVED",
                "IGNORED",
                name="sharepoint_sync_conflict_status",
            ),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column(
            "local_version_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "remote_version_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column(
            "resolution",
            sa.Enum(
                "KEEP_LOCAL",
                "KEEP_REMOTE",
                "KEEP_BOTH",
                "MERGE_METADATA",
                "IGNORE_REMOTE_CHANGE",
                "IGNORE_LOCAL_CHANGE",
                name="sharepoint_sync_conflict_resolution",
            ),
            nullable=True,
        ),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_comment", sa.Text(), nullable=True),
        sa.Column("result_document_file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name=op.f("fk_sharepoint_sync_conflicts_assigned_to_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_file_id"],
            ["document_files.id"],
            name=op.f("fk_sharepoint_sync_conflicts_document_file_id_document_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_sharepoint_sync_conflicts_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revisions.id"],
            name=op.f(
                "fk_sharepoint_sync_conflicts_document_revision_id_document_revisions"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
            name=op.f("fk_sharepoint_sync_conflicts_resolved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["result_document_file_id"],
            ["document_files.id"],
            name=op.f(
                "fk_sharepoint_sync_conflicts_result_document_file_id_document_files"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sync_item_id"],
            ["sharepoint_sync_items.id"],
            name="fk_sharepoint_sync_conflicts_item",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["sync_job_id"],
            ["sharepoint_sync_jobs.id"],
            name=op.f("fk_sharepoint_sync_conflicts_sync_job_id_sharepoint_sync_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharepoint_sync_conflicts")),
    )
    op.create_index(
        "ix_sharepoint_sync_conflicts_detected",
        "sharepoint_sync_conflicts",
        ["detected_at"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_conflicts_file",
        "sharepoint_sync_conflicts",
        ["document_file_id"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_conflicts_job",
        "sharepoint_sync_conflicts",
        ["sync_job_id"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_conflicts_status",
        "sharepoint_sync_conflicts",
        ["status"],
        unique=False,
    )
    op.create_table(
        "sharepoint_sync_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sync_job_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("document_revision_id", sa.Uuid(), nullable=True),
        sa.Column("document_file_id", sa.Uuid(), nullable=True),
        sa.Column("remote_drive_id", sa.String(length=1000), nullable=True),
        sa.Column("remote_item_id", sa.String(length=1000), nullable=True),
        sa.Column("remote_path", sa.String(length=2000), nullable=True),
        sa.Column(
            "operation",
            sa.Enum(
                "CREATE_REMOTE",
                "UPDATE_REMOTE",
                "CREATE_LOCAL",
                "UPDATE_LOCAL",
                "MOVE_REMOTE",
                "RENAME_REMOTE",
                "UPDATE_REMOTE_METADATA",
                "UPDATE_LOCAL_METADATA",
                "REMOTE_DELETE_DETECTED",
                "LOCAL_DELETE_DETECTED",
                "SKIP",
                "CONFLICT",
                name="sharepoint_sync_item_operation",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "PROCESSING",
                "COMPLETED",
                "SKIPPED",
                "CONFLICT",
                "FAILED",
                "CANCELLED",
                "DEAD_LETTER",
                name="sharepoint_sync_item_status",
            ),
            server_default="QUEUED",
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("local_hash_before", sa.String(length=64), nullable=True),
        sa.Column("local_hash_after", sa.String(length=64), nullable=True),
        sa.Column("remote_etag_before", sa.String(length=1000), nullable=True),
        sa.Column("remote_etag_after", sa.String(length=1000), nullable=True),
        sa.Column("remote_size", sa.BigInteger(), nullable=True),
        sa.Column("conflict_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conflict_id"],
            ["sharepoint_sync_conflicts.id"],
            name="fk_sharepoint_sync_items_conflict",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["document_file_id"],
            ["document_files.id"],
            name=op.f("fk_sharepoint_sync_items_document_file_id_document_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_sharepoint_sync_items_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revisions.id"],
            name=op.f(
                "fk_sharepoint_sync_items_document_revision_id_document_revisions"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sync_job_id"],
            ["sharepoint_sync_jobs.id"],
            name=op.f("fk_sharepoint_sync_items_sync_job_id_sharepoint_sync_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharepoint_sync_items")),
        sa.UniqueConstraint(
            "idempotency_key", name="uq_sharepoint_sync_items_idempotency_key"
        ),
    )
    op.create_index(
        "ix_sharepoint_sync_items_file",
        "sharepoint_sync_items",
        ["document_file_id"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_items_job",
        "sharepoint_sync_items",
        ["sync_job_id"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_items_remote",
        "sharepoint_sync_items",
        ["remote_drive_id", "remote_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_sharepoint_sync_items_status",
        "sharepoint_sync_items",
        ["status"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_sharepoint_sync_conflicts_item",
        "sharepoint_sync_conflicts",
        "sharepoint_sync_items",
        ["sync_item_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_sharepoint_sync_items_conflict",
        "sharepoint_sync_items",
        "sharepoint_sync_conflicts",
        ["conflict_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "document_files",
        sa.Column("sharepoint_connection_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "document_files",
        sa.Column("remote_drive_id", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "document_files",
        sa.Column("remote_item_id", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "document_files",
        sa.Column("remote_parent_item_id", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "document_files",
        sa.Column("remote_path", sa.String(length=2000), nullable=True),
    )
    op.add_column(
        "document_files", sa.Column("remote_web_url", sa.Text(), nullable=True)
    )
    op.add_column(
        "document_files",
        sa.Column("remote_etag", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "document_files",
        sa.Column("remote_ctag", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "document_files",
        sa.Column("remote_version_id", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "document_files",
        sa.Column("remote_last_modified_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "document_files",
        sa.Column("remote_last_modified_by", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "document_files", sa.Column("remote_size", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "document_files",
        sa.Column("remote_mime_type", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "document_files",
        sa.Column(
            "remote_sync_status",
            sa.String(length=50),
            server_default="NOT_SYNCED",
            nullable=False,
        ),
    )
    op.add_column(
        "document_files",
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "document_files",
        sa.Column("sync_error_code", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "document_files", sa.Column("sync_error_message", sa.Text(), nullable=True)
    )
    op.execute(
        sa.text("UPDATE document_files SET storage_provider = upper(storage_provider)")
    )
    op.alter_column(
        "document_files",
        "storage_provider",
        existing_type=sa.VARCHAR(length=50),
        server_default="LOCAL",
        existing_nullable=False,
    )
    op.create_check_constraint(
        op.f("ck_document_files_storage_provider_valid"),
        "document_files",
        "storage_provider IN ('LOCAL', 'SHAREPOINT', 'HYBRID')",
    )
    op.create_check_constraint(
        op.f("ck_document_files_remote_size_nonnegative"),
        "document_files",
        "remote_size IS NULL OR remote_size >= 0",
    )
    op.create_check_constraint(
        op.f("ck_document_files_remote_sync_status_valid"),
        "document_files",
        "remote_sync_status IN "
        "('NOT_SYNCED', 'PENDING', 'SYNCING', 'SYNCED', 'CONFLICT', "
        "'FAILED', 'REMOTE_MISSING', 'DISABLED')",
    )
    op.create_index(
        "ix_document_files_remote_item_id",
        "document_files",
        ["remote_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_document_files_remote_sync_status",
        "document_files",
        ["remote_sync_status"],
        unique=False,
    )
    op.create_index(
        "ix_document_files_sharepoint_connection_id",
        "document_files",
        ["sharepoint_connection_id"],
        unique=False,
    )
    op.create_index(
        "ix_document_files_storage_provider",
        "document_files",
        ["storage_provider"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_document_files_sharepoint_connection_id_sharepoint_connections"),
        "document_files",
        "sharepoint_connections",
        ["sharepoint_connection_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            sa.text(
                "ALTER TABLE sharepoint_sync_items "
                "DROP CONSTRAINT IF EXISTS fk_sharepoint_sync_items_conflict"
            )
        )
        op.execute(
            sa.text(
                "ALTER TABLE sharepoint_sync_conflicts "
                "DROP CONSTRAINT IF EXISTS fk_sharepoint_sync_conflicts_item"
            )
        )
    else:
        op.drop_constraint(
            "fk_sharepoint_sync_items_conflict",
            "sharepoint_sync_items",
            type_="foreignkey",
        )
        op.drop_constraint(
            "fk_sharepoint_sync_conflicts_item",
            "sharepoint_sync_conflicts",
            type_="foreignkey",
        )
    op.drop_constraint(
        op.f("fk_document_files_sharepoint_connection_id_sharepoint_connections"),
        "document_files",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("ck_document_files_remote_sync_status_valid"),
        "document_files",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_document_files_remote_size_nonnegative"),
        "document_files",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_document_files_storage_provider_valid"),
        "document_files",
        type_="check",
    )
    op.drop_index("ix_document_files_storage_provider", table_name="document_files")
    op.drop_index(
        "ix_document_files_sharepoint_connection_id", table_name="document_files"
    )
    op.drop_index("ix_document_files_remote_sync_status", table_name="document_files")
    op.drop_index("ix_document_files_remote_item_id", table_name="document_files")
    op.alter_column(
        "document_files",
        "storage_provider",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'local'::character varying"),
        existing_nullable=False,
    )
    op.execute(
        sa.text("UPDATE document_files SET storage_provider = lower(storage_provider)")
    )
    op.drop_column("document_files", "sync_error_message")
    op.drop_column("document_files", "sync_error_code")
    op.drop_column("document_files", "last_synced_at")
    op.drop_column("document_files", "remote_sync_status")
    op.drop_column("document_files", "remote_mime_type")
    op.drop_column("document_files", "remote_size")
    op.drop_column("document_files", "remote_last_modified_by")
    op.drop_column("document_files", "remote_last_modified_at")
    op.drop_column("document_files", "remote_version_id")
    op.drop_column("document_files", "remote_ctag")
    op.drop_column("document_files", "remote_etag")
    op.drop_column("document_files", "remote_web_url")
    op.drop_column("document_files", "remote_path")
    op.drop_column("document_files", "remote_parent_item_id")
    op.drop_column("document_files", "remote_item_id")
    op.drop_column("document_files", "remote_drive_id")
    op.drop_column("document_files", "sharepoint_connection_id")
    op.drop_index("ix_sharepoint_sync_items_status", table_name="sharepoint_sync_items")
    op.drop_index("ix_sharepoint_sync_items_remote", table_name="sharepoint_sync_items")
    op.drop_index("ix_sharepoint_sync_items_job", table_name="sharepoint_sync_items")
    op.drop_index("ix_sharepoint_sync_items_file", table_name="sharepoint_sync_items")
    op.drop_table("sharepoint_sync_items")
    op.drop_index(
        "ix_sharepoint_sync_conflicts_status", table_name="sharepoint_sync_conflicts"
    )
    op.drop_index(
        "ix_sharepoint_sync_conflicts_job", table_name="sharepoint_sync_conflicts"
    )
    op.drop_index(
        "ix_sharepoint_sync_conflicts_file", table_name="sharepoint_sync_conflicts"
    )
    op.drop_index(
        "ix_sharepoint_sync_conflicts_detected", table_name="sharepoint_sync_conflicts"
    )
    op.drop_table("sharepoint_sync_conflicts")
    op.drop_index(
        "ix_sharepoint_file_versions_remote", table_name="sharepoint_file_versions"
    )
    op.drop_index(
        "ix_sharepoint_file_versions_file", table_name="sharepoint_file_versions"
    )
    op.drop_table("sharepoint_file_versions")
    op.drop_index(
        "ix_sharepoint_delta_states_valid", table_name="sharepoint_delta_states"
    )
    op.drop_index(
        "ix_sharepoint_delta_states_synced_at", table_name="sharepoint_delta_states"
    )
    op.drop_table("sharepoint_delta_states")
    op.drop_index("ix_graph_webhook_events_status", table_name="graph_webhook_events")
    op.drop_index("ix_graph_webhook_events_received", table_name="graph_webhook_events")
    op.drop_table("graph_webhook_events")
    op.drop_index(
        "uq_sharepoint_sync_jobs_active_profile",
        table_name="sharepoint_sync_jobs",
        postgresql_where=sa.text(
            "status IN ('COMPARING', 'TRANSFERRING', 'CANCEL_REQUESTED', 'PERSISTING', 'UPDATING_METADATA', 'QUEUED', 'DISCOVERING', 'AUTHENTICATING', 'RESOLVING_CONFLICTS')"
        ),
        sqlite_where=sa.text(
            "status IN ('COMPARING', 'TRANSFERRING', 'CANCEL_REQUESTED', 'PERSISTING', 'UPDATING_METADATA', 'QUEUED', 'DISCOVERING', 'AUTHENTICATING', 'RESOLVING_CONFLICTS')"
        ),
    )
    op.drop_index("ix_sharepoint_sync_jobs_status", table_name="sharepoint_sync_jobs")
    op.drop_index(
        "ix_sharepoint_sync_jobs_requested_at", table_name="sharepoint_sync_jobs"
    )
    op.drop_index("ix_sharepoint_sync_jobs_profile", table_name="sharepoint_sync_jobs")
    op.drop_index(
        "ix_sharepoint_sync_jobs_connection", table_name="sharepoint_sync_jobs"
    )
    op.drop_table("sharepoint_sync_jobs")
    op.drop_index("ix_graph_subscriptions_status", table_name="graph_subscriptions")
    op.drop_index("ix_graph_subscriptions_expiration", table_name="graph_subscriptions")
    op.drop_table("graph_subscriptions")
    op.drop_index(
        "ix_sharepoint_sync_profiles_scope", table_name="sharepoint_sync_profiles"
    )
    op.drop_index(
        "ix_sharepoint_sync_profiles_connection", table_name="sharepoint_sync_profiles"
    )
    op.drop_index(
        "ix_sharepoint_sync_profiles_active", table_name="sharepoint_sync_profiles"
    )
    op.drop_table("sharepoint_sync_profiles")
    op.drop_index(
        "ix_sharepoint_folder_mappings_resolution",
        table_name="sharepoint_folder_mappings",
    )
    op.drop_index(
        "ix_sharepoint_folder_mappings_connection",
        table_name="sharepoint_folder_mappings",
    )
    op.drop_table("sharepoint_folder_mappings")
    op.drop_index(
        "ix_sharepoint_metadata_mappings_connection",
        table_name="sharepoint_metadata_mappings",
    )
    op.drop_index(
        "ix_sharepoint_metadata_mappings_active",
        table_name="sharepoint_metadata_mappings",
    )
    op.drop_table("sharepoint_metadata_mappings")
    op.drop_index("ix_notification_rules_resolution", table_name="notification_rules")
    op.drop_index("ix_notification_rules_is_active", table_name="notification_rules")
    op.drop_index("ix_notification_rules_event_type", table_name="notification_rules")
    op.drop_index(
        "ix_notification_rules_document_type_id", table_name="notification_rules"
    )
    op.drop_index(
        "ix_notification_rules_department_id", table_name="notification_rules"
    )
    op.drop_index("ix_notification_rules_channel", table_name="notification_rules")
    op.drop_table("notification_rules")
    op.drop_index(
        "ix_notification_deliveries_status", table_name="notification_deliveries"
    )
    op.drop_index(
        "ix_notification_deliveries_retry_queue", table_name="notification_deliveries"
    )
    op.drop_index(
        "ix_notification_deliveries_next_retry_at", table_name="notification_deliveries"
    )
    op.drop_index(
        "ix_notification_deliveries_event_type", table_name="notification_deliveries"
    )
    op.drop_index(
        "ix_notification_deliveries_created_at", table_name="notification_deliveries"
    )
    op.drop_index(
        "ix_notification_deliveries_channel", table_name="notification_deliveries"
    )
    op.drop_table("notification_deliveries")
    op.drop_index(
        "ix_data_retention_policies_is_active", table_name="data_retention_policies"
    )
    op.drop_index(
        "ix_data_retention_policies_entity_type", table_name="data_retention_policies"
    )
    op.drop_index(
        "ix_data_retention_policies_document_type_id",
        table_name="data_retention_policies",
    )
    op.drop_index(
        "ix_data_retention_policies_department_id", table_name="data_retention_policies"
    )
    op.drop_table("data_retention_policies")
    op.drop_index(
        "uq_sharepoint_connections_default",
        table_name="sharepoint_connections",
        postgresql_where=sa.text("is_default IS TRUE AND is_active IS TRUE"),
        sqlite_where=sa.text("is_default = 1 AND is_active = 1"),
    )
    op.drop_index(
        "ix_sharepoint_connections_status", table_name="sharepoint_connections"
    )
    op.drop_index(
        "ix_sharepoint_connections_active", table_name="sharepoint_connections"
    )
    op.drop_table("sharepoint_connections")
    op.drop_index(
        "ix_notification_templates_resolution", table_name="notification_templates"
    )
    op.drop_index(
        "ix_notification_templates_is_active", table_name="notification_templates"
    )
    op.drop_index(
        "ix_notification_templates_event_type", table_name="notification_templates"
    )
    op.drop_index(
        "ix_notification_templates_channel", table_name="notification_templates"
    )
    op.drop_table("notification_templates")
    op.drop_index(
        "ix_notification_preferences_user_id", table_name="notification_preferences"
    )
    op.drop_index(
        "ix_notification_preferences_event_type", table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(
        "ix_in_app_notifications_user_unread", table_name="in_app_notifications"
    )
    op.drop_index("ix_in_app_notifications_user_id", table_name="in_app_notifications")
    op.drop_index("ix_in_app_notifications_is_read", table_name="in_app_notifications")
    op.drop_index(
        "ix_in_app_notifications_expires_at", table_name="in_app_notifications"
    )
    op.drop_index(
        "ix_in_app_notifications_event_type", table_name="in_app_notifications"
    )
    op.drop_index(
        "ix_in_app_notifications_created_at", table_name="in_app_notifications"
    )
    op.drop_table("in_app_notifications")
    op.drop_index("ix_dead_letter_jobs_task_name", table_name="dead_letter_jobs")
    op.drop_index("ix_dead_letter_jobs_status", table_name="dead_letter_jobs")
    op.drop_index("ix_dead_letter_jobs_last_failed", table_name="dead_letter_jobs")
    op.drop_table("dead_letter_jobs")
    op.drop_index("ix_worker_heartbeats_worker_name", table_name="worker_heartbeats")
    op.drop_index("ix_worker_heartbeats_queue_name", table_name="worker_heartbeats")
    op.drop_index(
        "ix_worker_heartbeats_last_heartbeat_at", table_name="worker_heartbeats"
    )
    op.drop_table("worker_heartbeats")
    _drop_phase10_enum_types()
    # ### end Alembic commands ###
