import type { AuthSession } from '../types/auth';

export const superAdminSession: AuthSession = {
  accessToken: 'test-access-token',
  refreshToken: 'test-refresh-token',
  tokenType: 'bearer',
  expiresIn: 900,
  user: {
    id: '69e87427-d98e-4a62-b787-b1c07362b11e',
    name: 'System Administrator',
    email: 'admin@example.com',
    role: 'SUPER_ADMIN',
    departmentId: null,
    isActive: true,
  },
  permissions: [
    'dashboard:view',
    'documents:view',
    'documents:create',
    'documents:update',
    'documents:archive',
    'documents:restore',
    'documents:export',
    'documents:import',
    'documents:view_all_departments',
    'documents:manage_revisions',
    'documents:upload',
    'documents:download',
    'documents:replace_file',
    'documents:delete_file',
    'documents:batch_upload',
    'documents:view_file_history',
    'documents:extract',
    'documents:reextract',
    'documents:view_extracted_content',
    'documents:export_extracted_content',
    'documents:view_extraction_history',
    'documents:cancel_extraction',
    'documents:ocr',
    'documents:reocr',
    'documents:view_ocr_results',
    'documents:view_ocr_history',
    'documents:cancel_ocr',
    'documents:detect_language',
    'documents:redetect_language',
    'documents:view_language_results',
    'documents:export_language_results',
    'documents:review_language_result',
    'compliance:view',
    'compliance:validate',
    'compliance:revalidate',
    'compliance:view_all_departments',
    'compliance:export',
    'compliance:configure_rules',
    'findings:view',
    'findings:create_manual',
    'findings:update',
    'findings:review',
    'findings:resolve',
    'findings:reopen',
    'findings:false_positive',
    'findings:export',
    'reports:view',
    'reports:export',
    'master_data:view',
    'master_data:create',
    'master_data:update',
    'master_data:delete',
    'users:view',
    'settings:view',
  ],
};
