import type {
  ComplianceJob,
  ComplianceRun,
  ComplianceScoreBreakdown,
  ComplianceSummary,
  DetectedSection,
  TranslationGroup,
} from '../types/compliance';
import type { Finding, FindingListItem } from '../types/finding';

export const phase8Ids = {
  job: '80000000-0000-4000-8000-000000000001',
  run: '80000000-0000-4000-8000-000000000002',
  previousRun: '80000000-0000-4000-8000-000000000003',
  document: '80000000-0000-4000-8000-000000000004',
  revision: '80000000-0000-4000-8000-000000000005',
  file: '80000000-0000-4000-8000-000000000006',
  rule: '80000000-0000-4000-8000-000000000007',
  finding: '80000000-0000-4000-8000-000000000008',
  section: '80000000-0000-4000-8000-000000000009',
  group: '80000000-0000-4000-8000-000000000010',
  extraction: '80000000-0000-4000-8000-000000000011',
  language: '80000000-0000-4000-8000-000000000012',
} as const;

const document = {
  id: phase8Ids.document,
  baseDocumentCode: 'MTI-HRM-SOP-0042',
  title: 'Employee Onboarding',
  departmentId: '80000000-0000-4000-8000-000000000013',
  departmentName: 'Human Resources',
};

const revision = {
  id: phase8Ids.revision,
  revisionCode: 'Rev.002',
  fullDocumentCode: 'MTI-HRM-SOP-0042-Rev.002',
};

const validationRule = {
  id: phase8Ids.rule,
  code: 'SOP-3LANG',
  name: 'SOP Three-Language Rule',
  version: 3,
};

export const complianceJob = {
  id: phase8Ids.job,
  documentId: phase8Ids.document,
  documentRevisionId: phase8Ids.revision,
  documentFileId: phase8Ids.file,
  document,
  revision,
  file: {
    id: phase8Ids.file,
    filename: 'MTI-HRM-SOP-0042-Rev.002.docx',
    fileExtension: 'docx',
  },
  validationRule,
  jobType: 'INITIAL_VALIDATION',
  status: 'VALIDATING_LANGUAGES',
  progress: 45,
  currentStage: 'VALIDATING_LANGUAGES',
  requestedBy: {
    id: '80000000-0000-4000-8000-000000000014',
    name: 'Document Controller',
  },
  requestedAt: '2026-07-26T08:00:00+08:00',
  startedAt: '2026-07-26T08:00:01+08:00',
  completedAt: null,
  failedAt: null,
  cancelledAt: null,
  attemptNumber: 1,
  maximumAttempts: 2,
  errorCode: null,
  errorMessage: null,
  resultSummary: null,
} satisfies ComplianceJob;

export const complianceRun = {
  id: phase8Ids.run,
  complianceJobId: phase8Ids.job,
  documentId: phase8Ids.document,
  documentRevisionId: phase8Ids.revision,
  documentFileId: phase8Ids.file,
  extractionRunId: phase8Ids.extraction,
  ocrRunId: null,
  languageDetectionRunId: phase8Ids.language,
  validationRuleId: phase8Ids.rule,
  document,
  revision,
  file: {
    id: phase8Ids.file,
    filename: 'MTI-HRM-SOP-0042-Rev.002.docx',
    fileExtension: 'docx',
  },
  validationRule,
  ruleSnapshot: {
    requiredLanguages: ['id', 'en', 'zh'],
    languageOrder: ['id', 'en', 'zh'],
  },
  sourceContentHash: 'sha256-source-content',
  status: 'COMPLETED',
  complianceStatus: 'NEEDS_REVIEW',
  complianceScore: 82.5,
  maximumScore: 100,
  documentCodeScore: 10,
  languagePresenceScore: 25,
  languageCoverageScore: 13,
  sectionCompletenessScore: 16,
  languageOrderScore: 8,
  translationGroupScore: 8.5,
  tableCompletenessScore: 2,
  totalFindings: 10,
  criticalFindings: 0,
  majorFindings: 3,
  minorFindings: 6,
  informationFindings: 1,
  openFindings: 9,
  requiredLanguages: ['id', 'en', 'zh'],
  detectedLanguages: ['id', 'en'],
  missingLanguages: ['zh'],
  requiredSections: ['TITLE', 'PURPOSE', 'SCOPE'],
  detectedSections: ['TITLE', 'SCOPE'],
  missingSections: ['PURPOSE'],
  warnings: ['Low grouping confidence requires manual review.'],
  metrics: {},
  startedAt: '2026-07-26T08:00:01+08:00',
  completedAt: '2026-07-26T08:01:00+08:00',
  requestedBy: {
    id: '80000000-0000-4000-8000-000000000014',
    name: 'Document Controller',
  },
  createdAt: '2026-07-26T08:01:00+08:00',
} satisfies ComplianceRun;

export const complianceSummary = {
  runId: phase8Ids.run,
  status: 'COMPLETED',
  complianceStatus: 'NEEDS_REVIEW',
  complianceScore: 82.5,
  requiredLanguages: ['id', 'en', 'zh'],
  languagePresence: {
    id: 'PRESENT',
    en: 'PRESENT',
    zh: 'NOT_PRESENT',
  },
  languageCoverage: { id: 35, en: 34, zh: 0 },
  languageMetrics: [
    {
      languageCode: 'id',
      presence: 'PRESENT',
      blockCoverage: 35,
      characterCoverage: 36,
      minimumBlockCoverage: 20,
      minimumCharacterCoverage: 20,
      averageConfidence: 0.96,
      findingCount: 0,
    },
    {
      languageCode: 'en',
      presence: 'PRESENT',
      blockCoverage: 34,
      characterCoverage: 35,
      minimumBlockCoverage: 20,
      minimumCharacterCoverage: 20,
      averageConfidence: 0.94,
      findingCount: 0,
    },
    {
      languageCode: 'zh',
      presence: 'NOT_PRESENT',
      blockCoverage: 0,
      characterCoverage: 0,
      minimumBlockCoverage: 20,
      minimumCharacterCoverage: 20,
      averageConfidence: null,
      findingCount: 2,
    },
  ],
  missingLanguages: ['zh'],
  requiredSections: 3,
  detectedSections: 2,
  completeSections: 1,
  missingSections: ['PURPOSE'],
  translationGroups: { total: 4, complete: 2, incomplete: 2, lowConfidence: 1 },
  findings: {
    total: 10,
    critical: 0,
    major: 3,
    minor: 6,
    information: 1,
    open: 9,
  },
  warnings: ['Low grouping confidence requires manual review.'],
  prerequisiteErrors: [],
} satisfies ComplianceSummary;

export const scoreBreakdown = {
  documentCode: { earned: 10, maximum: 10 },
  languagePresence: { earned: 16.7, maximum: 25 },
  languageCoverage: { earned: 10, maximum: 15 },
  sectionCompleteness: { earned: 13.3, maximum: 20 },
  languageOrder: { earned: 8, maximum: 10 },
  translationGroups: { earned: 10, maximum: 15 },
  tableCompleteness: { earned: 4, maximum: 5 },
  penalties: { major: -5, minor: -1 },
  scoreCap: null,
  scoreCapReason: null,
  finalScore: 66,
} satisfies ComplianceScoreBreakdown;

export const detectedSection = {
  id: phase8Ids.section,
  complianceRunId: phase8Ids.run,
  sectionDefinitionId: '80000000-0000-4000-8000-000000000020',
  canonicalCode: 'PURPOSE',
  containerId: 'body',
  startBlockId: 'block-1',
  endBlockId: 'block-4',
  headingBlockId: 'block-1',
  headingText: '1. TUJUAN / PURPOSE / 目的',
  headingLanguageCode: 'mixed',
  matchType: 'EXACT',
  matchConfidence: 1,
  sectionOrder: 2,
  isRequired: true,
  isComplete: false,
  languagePresence: {
    id: 'PRESENT',
    en: 'PRESENT',
    zh: 'NOT_PRESENT',
  },
  languageResults: [],
  metrics: {},
  findingCount: 1,
  createdAt: '2026-07-26T08:01:00+08:00',
} satisfies DetectedSection;

export const translationGroup = {
  id: phase8Ids.group,
  complianceRunId: phase8Ids.run,
  containerId: 'body',
  detectedSectionId: phase8Ids.section,
  sectionCode: 'PURPOSE',
  groupIndex: 1,
  groupType: 'PARAGRAPH_GROUP',
  startBlockOrder: 1,
  endBlockOrder: 2,
  sourceReference: 'DOCX:body:p=4-5',
  expectedLanguages: ['id', 'en', 'zh'],
  detectedLanguages: ['id', 'en'],
  languageOrder: ['id', 'en'],
  actualLanguageOrder: ['id', 'en'],
  isComplete: false,
  isOrderValid: true,
  confidence: 0.91,
  metrics: {},
  members: [],
  findingCount: 1,
  createdAt: '2026-07-26T08:01:00+08:00',
} satisfies TranslationGroup;

export const finding = {
  id: phase8Ids.finding,
  complianceRunId: phase8Ids.run,
  documentId: phase8Ids.document,
  documentRevisionId: phase8Ids.revision,
  documentFileId: phase8Ids.file,
  validationRuleId: phase8Ids.rule,
  document,
  revision,
  validationRule,
  findingCode: 'MISSING_TRANSLATION_GROUP_CHINESE',
  findingType: 'TRANSLATION_GROUP_INCOMPLETE',
  severity: 'MAJOR',
  status: 'OPEN',
  title: 'Chinese content is missing from a translation group',
  description: 'A structurally grouped paragraph has Indonesian and English only.',
  recommendation: 'Review the source and add the required Chinese content.',
  containerId: 'body',
  detectedSectionId: phase8Ids.section,
  sectionCode: 'PURPOSE',
  translationGroupId: phase8Ids.group,
  extractedBlockId: 'block-4',
  ocrBlockId: null,
  pageNumber: null,
  worksheetName: null,
  cellCoordinate: null,
  sourceReference: 'DOCX:body:p=4-5',
  location: {},
  languageCode: 'zh',
  expectedValue: ['id', 'en', 'zh'],
  actualValue: ['id', 'en'],
  metrics: {},
  isSystemGenerated: true,
  isRepeat: false,
  previousFindingId: null,
  assignedTo: null,
  reviewedBy: null,
  reviewedAt: null,
  reviewComment: null,
  resolvedBy: null,
  resolvedAt: null,
  resolutionComment: null,
  falsePositiveBy: null,
  falsePositiveAt: null,
  falsePositiveReason: null,
  reopenedBy: null,
  reopenedAt: null,
  reopenReason: null,
  history: [],
  createdAt: '2026-07-26T08:01:00+08:00',
  updatedAt: '2026-07-26T08:01:00+08:00',
} satisfies Finding;

export const findingListItem = finding as FindingListItem;
