"""Stable, persistence-free constants used by the compliance engine.

The database layer owns its enums.  The engine intentionally works with their
wire values so it can also be exercised with Pydantic DTOs and simple test
objects without importing SQLAlchemy models.
"""

from __future__ import annotations

from enum import StrEnum

TARGET_LANGUAGES: tuple[str, ...] = ("id", "en", "zh")
NON_TARGET_LANGUAGES: frozenset[str] = frozenset(
    {"mixed", "unknown", "other"},
)


class ValidatorStatus(StrEnum):
    PASSED = "PASSED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    NOT_EVALUATED = "NOT_EVALUATED"
    SKIPPED = "SKIPPED"


class ComplianceStatus(StrEnum):
    COMPLIANT = "COMPLIANT"
    PARTIALLY_COMPLIANT = "PARTIALLY_COMPLIANT"
    NON_COMPLIANT = "NON_COMPLIANT"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    NOT_EVALUATED = "NOT_EVALUATED"


class FindingSeverity(StrEnum):
    CRITICAL = "CRITICAL"
    MAJOR = "MAJOR"
    MINOR = "MINOR"
    INFORMATION = "INFORMATION"


class FindingStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    ACCEPTED_RISK = "ACCEPTED_RISK"
    REOPENED = "REOPENED"


class FindingType(StrEnum):
    DOCUMENT_CODE = "DOCUMENT_CODE"
    LANGUAGE_PRESENCE = "LANGUAGE_PRESENCE"
    LANGUAGE_COVERAGE = "LANGUAGE_COVERAGE"
    SECTION_MISSING = "SECTION_MISSING"
    SECTION_LANGUAGE_MISSING = "SECTION_LANGUAGE_MISSING"
    SECTION_ORDER = "SECTION_ORDER"
    LANGUAGE_ORDER = "LANGUAGE_ORDER"
    TRANSLATION_GROUP_INCOMPLETE = "TRANSLATION_GROUP_INCOMPLETE"
    TABLE_LANGUAGE_MISSING = "TABLE_LANGUAGE_MISSING"
    CELL_LANGUAGE_MISSING = "CELL_LANGUAGE_MISSING"
    UNKNOWN_LANGUAGE_EXCESS = "UNKNOWN_LANGUAGE_EXCESS"
    MIXED_LANGUAGE_EXCESS = "MIXED_LANGUAGE_EXCESS"
    OCR_CONFIDENCE = "OCR_CONFIDENCE"
    EXTRACTION_QUALITY = "EXTRACTION_QUALITY"
    STRUCTURE = "STRUCTURE"
    MANUAL = "MANUAL"


class FindingCode(StrEnum):
    INVALID_DOCUMENT_CODE = "INVALID_DOCUMENT_CODE"
    MISSING_INDONESIAN = "MISSING_INDONESIAN"
    MISSING_ENGLISH = "MISSING_ENGLISH"
    MISSING_CHINESE = "MISSING_CHINESE"
    LOW_INDONESIAN_COVERAGE = "LOW_INDONESIAN_COVERAGE"
    LOW_ENGLISH_COVERAGE = "LOW_ENGLISH_COVERAGE"
    LOW_CHINESE_COVERAGE = "LOW_CHINESE_COVERAGE"
    MISSING_REQUIRED_SECTION = "MISSING_REQUIRED_SECTION"
    MISSING_SECTION_INDONESIAN = "MISSING_SECTION_INDONESIAN"
    MISSING_SECTION_ENGLISH = "MISSING_SECTION_ENGLISH"
    MISSING_SECTION_CHINESE = "MISSING_SECTION_CHINESE"
    SECTION_ORDER_INVALID = "SECTION_ORDER_INVALID"
    LANGUAGE_ORDER_INVALID = "LANGUAGE_ORDER_INVALID"
    INCOMPLETE_TRANSLATION_GROUP = "INCOMPLETE_TRANSLATION_GROUP"
    MISSING_TRANSLATION_GROUP_INDONESIAN = (
        "MISSING_TRANSLATION_GROUP_INDONESIAN"
    )
    MISSING_TRANSLATION_GROUP_ENGLISH = "MISSING_TRANSLATION_GROUP_ENGLISH"
    MISSING_TRANSLATION_GROUP_CHINESE = "MISSING_TRANSLATION_GROUP_CHINESE"
    TABLE_TRANSLATION_INCOMPLETE = "TABLE_TRANSLATION_INCOMPLETE"
    TABLE_CELL_LANGUAGE_MISSING = "TABLE_CELL_LANGUAGE_MISSING"
    XLSX_ROW_TRANSLATION_INCOMPLETE = "XLSX_ROW_TRANSLATION_INCOMPLETE"
    UNKNOWN_TEXT_EXCEEDS_THRESHOLD = "UNKNOWN_TEXT_EXCEEDS_THRESHOLD"
    MIXED_TEXT_EXCEEDS_THRESHOLD = "MIXED_TEXT_EXCEEDS_THRESHOLD"
    OCR_CONFIDENCE_TOO_LOW = "OCR_CONFIDENCE_TOO_LOW"
    EXTRACTION_PARTIALLY_COMPLETED = "EXTRACTION_PARTIALLY_COMPLETED"
    OCR_REQUIRED_NOT_COMPLETED = "OCR_REQUIRED_NOT_COMPLETED"
    MANUAL_FINDING = "MANUAL_FINDING"


LANGUAGE_NAMES: dict[str, str] = {
    "id": "Indonesian",
    "en": "English",
    "zh": "Chinese",
}

MISSING_LANGUAGE_CODES: dict[str, str] = {
    "id": FindingCode.MISSING_INDONESIAN,
    "en": FindingCode.MISSING_ENGLISH,
    "zh": FindingCode.MISSING_CHINESE,
}

LOW_COVERAGE_CODES: dict[str, str] = {
    "id": FindingCode.LOW_INDONESIAN_COVERAGE,
    "en": FindingCode.LOW_ENGLISH_COVERAGE,
    "zh": FindingCode.LOW_CHINESE_COVERAGE,
}

MISSING_SECTION_LANGUAGE_CODES: dict[str, str] = {
    "id": FindingCode.MISSING_SECTION_INDONESIAN,
    "en": FindingCode.MISSING_SECTION_ENGLISH,
    "zh": FindingCode.MISSING_SECTION_CHINESE,
}

MISSING_GROUP_LANGUAGE_CODES: dict[str, str] = {
    "id": FindingCode.MISSING_TRANSLATION_GROUP_INDONESIAN,
    "en": FindingCode.MISSING_TRANSLATION_GROUP_ENGLISH,
    "zh": FindingCode.MISSING_TRANSLATION_GROUP_CHINESE,
}

DEFAULT_WEIGHTS: dict[str, float] = {
    "document_code": 10.0,
    "language_presence": 25.0,
    "language_coverage": 15.0,
    "section_completeness": 20.0,
    "language_order": 10.0,
    "translation_group": 15.0,
    "table_completeness": 5.0,
}

DEFAULT_SECTION_ORDER: tuple[str, ...] = (
    "TITLE",
    "PURPOSE",
    "SCOPE",
    "DEFINITION",
    "REFERENCE",
    "RESPONSIBILITY",
    "PROCEDURE",
    "RECORDS",
    "ATTACHMENT",
    "REVISION_HISTORY",
    "APPROVAL",
    "DISTRIBUTION",
)

GROUP_TYPE_HEADING = "HEADING_GROUP"
GROUP_TYPE_PARAGRAPH = "PARAGRAPH_GROUP"
GROUP_TYPE_TABLE_ROW = "TABLE_ROW_GROUP"
GROUP_TYPE_TABLE_CELL = "TABLE_CELL_GROUP"
GROUP_TYPE_XLSX_ROW = "XLSX_ROW_GROUP"
GROUP_TYPE_PDF_POSITIONAL = "PDF_POSITIONAL_GROUP"

